import tkinter as tk
class Game(tk.Frame):
    def __init__(self):
        tk.Frame.__init__(self)
        self.grid()
        self.create()

    def create(self):
        self.picture0Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\校門-0000.gif")
        self.picture0= tk.Label(self, height=90, width=135, image=self.picture0Image)
        self.picture0.grid(row=0, column=0)
        self.picture18= tk.Label(self, height=6, width=20, bg="white")
        self.picture18.grid(row=0, column=1)
        self.picture1Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\管院-0000.gif")
        self.picture1= tk.Label(self, height=90, width=135, image=self.picture1Image)
        self.picture1.grid(row=0, column=2, columnspan=1)
        self.picture2Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\小福-0000.gif")
        self.picture2= tk.Label(self, height=90, width=135, image=self.picture2Image)
        self.picture2.grid(row=0, column=3, columnspan=1)
        self.picture3Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\新體-0000.gif")
        self.picture3= tk.Label(self, height=90, width=135, image=self.picture3Image)
        self.picture3.grid(row=0, column=4, columnspan=1)
        self.picture4Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\法學院-0000.gif")
        self.picture4= tk.Label(self, height=90, width=135, image=self.picture4Image)
        self.picture4.grid(row=0, column=5, columnspan=1)
        self.picture19= tk.Label(self, height=6, width=20, bg="white")
        self.picture19.grid(row=0, column=6, columnspan=1)
        self.picture5Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\文學院-0000.gif")
        self.picture5= tk.Label(self, height=90, width=135, image=self.picture5Image)
        self.picture5.grid(row=0, column=7, columnspan=1)
        self.picture20= tk.Label(self, height=6, width=20, bg="white")
        self.picture20.grid(row=1, column=0, columnspan=1)
        self.picture21= tk.Label(self, height=6, width=20, bg="white")
        self.picture21.grid(row=1, column=7, columnspan=1)
        self.picture17Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\水源-0000.gif")
        self.picture17= tk.Label(self, height=90, width=135, image=self.picture17Image)
        self.picture17.grid(row=2, column=0, columnspan=1)
        self.picture6Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\電資學院-0000.gif")
        self.picture6= tk.Label(self, height=90, width=135, image=self.picture6Image)
        self.picture6.grid(row=2, column=7, columnspan=1)
        self.picture16Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\傅鐘-0000.gif")
        self.picture16= tk.Label(self, height=90, width=135, image=self.picture16Image)
        self.picture16.grid(row=3, column=0, columnspan=1)
        self.picture7Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\活大-0000.gif")
        self.picture7= tk.Label(self, height=90, width=135, image=self.picture7Image)
        self.picture7.grid(row=3, column=7, columnspan=1)
        self.picture15Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\醉月湖-0000.gif")
        self.picture15= tk.Label(self, height=90, width=135, image=self.picture15Image)
        self.picture15.grid(row=4, column=0, columnspan=1)
        self.picture8= tk.Label(self, height=6, width=20, bg="white")
        self.picture8.grid(row=4, column=7, columnspan=1)
        self.picture22= tk.Label(self, height=6, width=20, bg="white")
        self.picture22.grid(row=5, column=0, columnspan=1)
        self.picture23= tk.Label(self, height=6, width=20, bg="white")
        self.picture23.grid(row=5, column=7, columnspan=1)
        self.picture14Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\總圖-0000.gif")
        self.picture14= tk.Label(self, height=90, width=135, image=self.picture14Image)
        self.picture14.grid(row=6, column=0, columnspan=1)
        self.picture24= tk.Label(self, height=6, width=20, bg="white")
        self.picture24.grid(row=6, column=1, columnspan=1)
        self.picture13Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\計中-0000.gif")
        self.picture13= tk.Label(self, height=90, width=135, image=self.picture13Image)
        self.picture13.grid(row=6, column=2, columnspan=1)
        self.picture12Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\宿舍-0000.gif")
        self.picture12= tk.Label(self, height=90, width=135, image=self.picture12Image)
        self.picture12.grid(row=6, column=3, columnspan=1)
        self.picture11Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\醫學院-0000.gif")
        self.picture11= tk.Label(self, height=90, width=135, image=self.picture11Image)
        self.picture11.grid(row=6, column=4, columnspan=1)
        self.picture10Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\理學院-0000.gif")
        self.picture10= tk.Label(self, height=90, width=135, image=self.picture10Image)
        self.picture10.grid(row=6, column=5, columnspan=1)
        self.picture25= tk.Label(self, height=6, width=20, bg="white")
        self.picture25.grid(row=6, column=6, columnspan=1)
        self.picture9Image=tk.PhotoImage(file="C:\\Users\\User\\Documents\\GitHub\\final_project\\final圖片\\社科院-0000.gif")
        self.picture9= tk.Label(self, height=90, width=135, image=self.picture9Image)
        self.picture9.grid(row=6, column=7, columnspan=1)

        self.place00 = tk.Label(self, height=5, width=15, bg='sky blue', text='校門\n\n ★ ❤ ✿ 😀 ', fg='white', font=('Arial', 12))
        self.place00.grid(row=1, column=1)
        self.place01 = tk.Label(self, height=5, width=15, bg='pink2', text='管院\n\n', fg='white', font=('Arial', 12))
        self.place01.grid(row=1, column=2)
        self.place02 = tk.Label(self, height=5, width=15, bg='sky blue', text='小福\n\n', fg='white', font=('Arial', 12))
        self.place02.grid(row=1, column=3)
        self.place03 = tk.Label(self, height=5, width=15, bg='pink2', text='新體\n\n', fg='white', font=('Arial', 12))
        self.place03.grid(row=1, column=4)
        self.place04 = tk.Label(self, height=5, width=15, bg='sky blue', text='法學院\n\n', fg='white', font=('Arial', 12))
        self.place04.grid(row=1, column=5)
        self.place05 = tk.Label(self, height=5, width=15, bg='pink2', text='文學院\n\n', fg='white', font=('Arial', 12))
        self.place05.grid(row=1, column=6)
        self.place06 = tk.Label(self, height=5, width=15, bg='sky blue', text='電資學院\n\n', fg='white', font=('Arial', 12))
        self.place06.grid(row=2, column=6)
        self.place07 = tk.Label(self, height=5, width=15, bg='pink2', text='活大\n\n', fg='white', font=('Arial', 12))
        self.place07.grid(row=3, column=6)
        self.place08 = tk.Label(self, height=5, width=15, bg='sky blue', text='機會/命運\n\n', fg='white', font=('Arial', 12))
        self.place08.grid(row=4, column=6)
        self.place09 = tk.Label(self, height=5, width=15, bg='pink2', text='社科院\n\n', fg='white', font=('Arial', 12))
        self.place09.grid(row=5, column=6)
        self.place10 = tk.Label(self, height=5, width=15, bg='sky blue', text='理學院\n\n', fg='white', font=('Arial', 12))
        self.place10.grid(row=5, column=5)
        self.place11 = tk.Label(self, height=5, width=15, bg='pink2', text='醫學院\n\n', fg='white', font=('Arial', 12))
        self.place11.grid(row=5, column=4)
        self.place12 = tk.Label(self, height=5, width=15, bg='sky blue', text='宿舍\n\n', fg='white', font=('Arial', 12))
        self.place12.grid(row=5, column=3)
        self.place13 = tk.Label(self, height=5, width=15, bg='pink2', text='計中\n\n', fg='white', font=('Arial', 12))
        self.place13.grid(row=5, column=2)
        self.place14 = tk.Label(self, height=5, width=15, bg='sky blue', text='總圖\n\n', fg='white', font=('Arial', 12))
        self.place14.grid(row=5, column=1)
        self.place15 = tk.Label(self, height=5, width=15, bg='pink2', text='醉月湖\n\n', fg='white', font=('Arial', 12))
        self.place15.grid(row=4, column=1)
        self.place16 = tk.Label(self, height=5, width=15, bg='sky blue', text='傅鐘\n\n', fg='white', font=('Arial', 12))
        self.place16.grid(row=3, column=1)
        self.place17 = tk.Label(self, height=5, width=15, bg='pink2', text='水源校區\n\n', fg='white', font=('Arial', 12))
        self.place17.grid(row=2, column=1)
        
        
        
game = Game()
game.mainloop()